services:
  google-home-voicetext:
    extra_hosts:
      - "k8s-81.local:10.15.8.81"
    build:
      context: ./
    container_name: "google-home-voicetext"
    working_dir: "/google-home-voicetext/"
    # ports:
    #   - "8082:8082"
    #   - "8083:8083"
    network_mode: "host"
    env_file:
      - ./.my.env
    tty: true
    restart: always

    volumes:
      - ./localCA.crt:/usr/local/share/ca-certificates/localCA.crt:ro
    environment:
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/localCA.crt