version: "3"

services:
  node-google-home:
    build:
      context: ./
    container_name: 'node-google-home'
    command: '/usr/local/bin/boot.bash'
    working_dir: '/google-home-voicetext/'
    volumes:
      - ./myapps/:/google-home-voicetext/
    ports:
      - '8080:8080'
      - '8888:8888'
    environment:
      - 'TZ=Asia/Tokyo'
      - 'VOICETEXT_API_KEY=4zgbtchmu6xgme5r'
      - 'WIRELESS_IP=10.10.254.14'
      - 'GOOGLE_HOME_IP=10.10.254.7'
