version: "3"

services:
  node-google-home:
    build:
      context: ./
    container_name: 'node-google-home'
    working_dir: '/google-home-voicetext/'
    ports:
      - '8080:8080'
      - '8888:8888'
    env_file:
      - ./.my.env
    tty: true
