version: "3"

services:
  google-home-voicetext:
    build:
      context: ./
    container_name: "google-home-voicetext"
    working_dir: "/google-home-voicetext/"
    # ports:
    #   - "8082:8082"
    #   - "8083:8083"
    network_mode: "host"
    env_file:
      - ./.my.env
    tty: true
    restart: always
