version: "3"

services:
  node-google-home:
    build:
      context: ./
    container_name: 'node-google-home'
    working_dir: '/google-home-voicetext/'
    ports:
      - '8082:8082'
      - '8083:8083'
    env_file:
      - ./.my.env
    tty: true
